### PR TITLE
Optimized loop bounds to allow the compiler to unroll the loop.

### PR DESCRIPTION
**Pull request by legrosbuffle**
This has no measurable impact on large files but improves small file
decompression by ~1-2% for 10kB, benchmarked with:

head -c 10000 silesia.tar > /tmp/test
make CC=/usr/local/bin/clang-9 BUILD_STATIC=1 && ./lzbench -ezstd -t1,5 /tmp/test

### CODE REVIEW

**Comment by terrelln** [comment]
Awesome! I'll look into benchmarking tomorrow, unless someone merges this before then.

**Comment by terrelln** [comment]
Sorry, I meant to benchmark this today, but my benchmark machine is turned off! I'll try to get to this tonight.

**Comment by bimbashrestha** [comment]
I can't reproduce the ~1-2% improvement mentioned on my desktop. I'm using the commit before this patch as the baseline and I get slower results every time when decompressing the compressed 10 KB silesia.tar file.

`head -c 1K silesia.tar > /tmp/test && ./zstd /tmp/test -o /tmp/test.zst`

Baseline: `./zstd -d -b /tmp/test.zst`
`3#test.zst          :      1024 ->       122 (8.393),  0.00 MB/s , 859.8 MB/s`
`3#test.zst          :      1024 ->       122 (8.393),  0.00 MB/s , 859.6 MB/s `
`3#test.zst          :      1024 ->       122 (8.393),  0.00 MB/s , 858.7 MB/s`

This patch: `./zstd -d -b /tmp/test.zst`
`3#test.zst          :      1024 ->       122 (8.393),  0.00 MB/s , 847.3 MB/s`
`3#test.zst          :      1024 ->       122 (8.393),  0.00 MB/s , 846.8 MB/s `
`3#test.zst          :      1024 ->       122 (8.393),  0.00 MB/s , 847.0 MB/s`

**Comment by terrelln** [comment]
I've measured a performance improvement with clang-9.0.0, and a performance decrease with gcc-9.2.0. Measured with `zstd -B10K -b silesia.tar`

| Compiler | Previous speed | New speed | Change |
| clang-9.0.0 | 917.7 MB/s | 932.9 MB/s | +1.5% |
| gcc-9.2.0 | 993.5 MB/s | 988.6 MB/s | -0.5% |

There is probably a version of this patch that doesn't regress gcc. Are you interested in continuing to work on it?

**Comment by terrelln** [comment]
With this diff I get positive perf on both clang and gcc.

| Compiler | Previous speed | New speed | Change |
|---|---|---|---|
| clang-9.0.0 | 917.7 MB/s | 941.7 MB/s | +2.6% |
| gcc-9.2.0 | 993.5 MB/s | 996.9 MB/s | +0.3% |


```diff
diff --git a/lib/decompress/huf_decompress.c b/lib/decompress/huf_decompress.c
index bb2d0a96..2f5747e0 100644
--- a/lib/decompress/huf_decompress.c
+++ b/lib/decompress/huf_decompress.c
@@ -180,17 +180,30 @@ size_t HUF_readDTableX1_wksp(HUF_DTable* DTable, const void* src, size_t srcSize
     }   }

     /* fill DTable */
-    {   U32 n;
-        for (n=0; n<nbSymbols; n++) {
-            U32 const w = huffWeight[n];
-            U32 const length = (1 << w) >> 1;
-            U32 u;
+    {   size_t n;
+       size_t const nEnd = nbSymbols;
+        for (n=0; n<nEnd; n++) {
+            size_t const w = huffWeight[n];
+            size_t const length = (1 << w) >> 1;
+            size_t const uStart = rankVal[w];
+            size_t const uEnd = uStart + length;
+            size_t u;
             HUF_DEltX1 D;
-            D.byte = (BYTE)n; D.nbBits = (BYTE)(tableLog + 1 - w);
-            for (u = rankVal[w]; u < rankVal[w] + length; u++)
-                dt[u] = D;
-            rankVal[w] += length;
-    }   }
+            D.byte = (BYTE)n;
+            D.nbBits = (BYTE)(tableLog + 1 - w);
+            rankVal[w] = uEnd;
+            if (length < 4) {
+                /* Use length in the loop bound so the compiler knows it is short. */
+                for (u = 0; u < length; ++u)
+                    dt[uStart + u] = D;
+            } else {
+                /* Unroll the loop 4 times, we know it is a power of 2. */
+                for (u = uStart; u < uEnd; u += 4) {
+                    dt[u + 0] = D;
+                    dt[u + 1] = D;
+                    dt[u + 2] = D;
+                    dt[u + 3] = D;
+    }   }   }   }

     return iSize;
 }
```

**Comment by legrosbuffle** [comment]
Sorry for the delay, and thank you both for investigating. We're using clang, I admit that I did not try with gcc.

I've updated the patch with your unrolled version.

**Comment by terrelln** [comment]
Thanks for the patch @legrosbuffle!

**Pull request merged**
