### PR TITLE
[RFC] Create CodeQL Workflow

### PR DESCRIPTION
**Pull request by felixhandte**
Creates the workflow suggested by #3269.

### CODE REVIEW

**Comment by felixhandte** [comment]
Looks like this produced 0 alerts...: https://github.com/facebook/zstd/security/code-scanning?query=is%3Aopen+pr%3A3270

Not totally sure I've done this right. Alternatively, maybe our code is perfect.

**Comment by Cyan4973** [comment]
I'm a bit lost here, as #3269 is about Google OpenSSF ScoreCard,
while this PR seems more about Github CodeQL Action.

Both seem valid and interesting, but they seem different, complementary maybe.

**Comment by Cyan4973** [comment]
> Looks like this produced 0 alerts...: https://github.com/facebook/zstd/security/code-scanning?query=is%3Aopen+pr%3A3270
> 
> Not totally sure I've done this right. Alternatively, maybe our code is perfect.

Well, if this tool only throws alerts when it's pretty sure to have found something worth investigating,
then it's not too far from expectation.
After all, we are already using a lot of bug mitigation techniques in this code base.

And if that's the reason, it's a good thing :  
I very much prefer a tool which alert level can be trusted, and therefore acted upon,
as opposed to tools which send too many alerts in the hope that maybe one of them might be interesting, 
thus destroying the value of the alert itself.

Now, of course, as a first test, it opens the possibility that it might simply be not working at all.
To cover this risk, try to enable this workflow on another code base,
one that you know should (or make up to) trigger some kind of CodeQL warning because it's obviously wrong.

**Comment by felixhandte** [comment]
So indeed, trying it on a PR on my fork with obviously incorrect code failed to produce any alerts: https://github.com/felixhandte/zstd/security/code-scanning?query=is%3Aopen+pr%3A10+. I'm not going to invest more effort into this now.

**Pull request closed without merging**
