### PR TITLE
Enabled multi-threading in MSYS CMake build

### PR DESCRIPTION
**Pull request by nowakowsk**
MSYS environment comes with pthreads, so it makes sense to enable this library in MSYS builds. It's an easy way of getting multi-threading on Windows.

I am not sure if I am allowed to sign CLA without violating my current contract, so please **do not consider this a contribution**. I am just pointing out a possible improvement. Thanks.

### CODE REVIEW

**Comment by lazka** [comment]
Are you sure UNIX isn't true under MSYS?

**Comment by nowakowsk** [comment]
Pretty sure. To verify that I made a simple CMake project:
```
cmake_minimum_required(VERSION 3.10)

project(test)

set(THREADS_PREFER_PTHREAD_FLAG ON)

find_package(Threads)

message(STATUS "CMAKE_THREAD_LIBS_INIT: ${CMAKE_THREAD_LIBS_INIT}")
message(STATUS "CMAKE_USE_SPROC_INIT: ${CMAKE_USE_SPROC_INIT}")
message(STATUS "CMAKE_USE_WIN32_THREADS_INIT: ${CMAKE_USE_WIN32_THREADS_INIT}")
message(STATUS "CMAKE_USE_PTHREADS_INIT: ${CMAKE_USE_PTHREADS_INIT}")
message(STATUS "CMAKE_HP_PTHREADS_INIT: ${CMAKE_HP_PTHREADS_INIT}")
message(STATUS "UNIX: ${UNIX}")
message(STATUS "MSYS: ${MSYS}")
message(STATUS "WIN32: ${WIN32}")
```
Here is the output from MSYS shell:
```
# cmake -G "MSYS Makefiles" ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- CMAKE_THREAD_LIBS_INIT:
-- CMAKE_USE_SPROC_INIT:
-- CMAKE_USE_WIN32_THREADS_INIT: 1
-- CMAKE_USE_PTHREADS_INIT: 1
-- CMAKE_HP_PTHREADS_INIT:
-- UNIX:
-- MSYS: 1
-- WIN32: 1
```
I ran some tests and CPU utilization during compression is much better after these changes. In some scenarios I get full CPU saturation.

**Comment by lazka** [comment]
ah, mingw, I assumed cygwin.

A quick look at the code shows that there is a pthread shim for Windows included in zstd: https://github.com/facebook/zstd/blob/16654625738d26ea8344eb4fb615bcbffd30b7f0/lib/common/threading.c so making the build set ZSTD_MULTITHREAD under Windows should help both gcc and msvc.

But your solution to use the mingw pthreads emulation also works, so never mind my comment above.

**Comment by nowakowsk** [comment]
You are right, I missed this pthreads wrapper. It probably makes more sense to use it than to rely on a third party pthreads implementation from MSYS. I am closing this PR. Thanks!

**Pull request closed without merging**
