### PR TITLE
Removing symbols already in unit tests and adding some new unit tests for missing symbols

### PR DESCRIPTION
**Pull request by bimbashrestha**
Script used to find missing symbols. Only checks in `test_filenames` because those are the ones that our CI currently uses. 
 
```
symbols = [
    "ZSTD_versionNumber",
    "ZSTD_compress",
    "ZSTD_decompress",
    "ZSTD_getDecompressedSize",
    "ZSTD_findDecompressedSize",
    "ZSTD_findFrameCompressedSize",
    "ZSTD_getFrameContentSize",
    "ZSTD_maxCLevel",
    "ZSTD_compressBound",
    "ZSTD_decompressBound",
    "ZSTD_isError",
    "ZSTD_getErrorName",
    "ZSTD_createCCtx",
    "ZSTD_freeCCtx",
    "ZSTD_compressCCtx",
    "ZSTD_createDCtx",
    "ZSTD_freeDCtx",
    "ZSTD_decompressDCtx",
    "ZSTD_compress_usingDict",
    "ZSTD_decompress_usingDict",
    "ZSTD_createCDict",
    "ZSTD_freeCDict",
    "ZSTD_compress_usingCDict",
    "ZSTD_createDDict",
    "ZSTD_freeDDict",
    "ZSTD_decompress_usingDDict",
    "ZSTD_createCStream",
    "ZSTD_freeCStream",
    "ZSTD_initCStream",
    "ZSTD_compressStream",
    "ZSTD_flushStream",
    "ZSTD_endStream",
    "ZSTD_CStreamInSize",
    "ZSTD_CStreamOutSize",
    "ZSTD_createDStream",
    "ZSTD_freeDStream",
    "ZSTD_initDStream",
    "ZSTD_decompressStream",
    "ZSTD_DStreamInSize",
    "ZSTD_DStreamOutSize",
    "ZSTD_estimateCCtxSize",
    "ZSTD_createCCtx_advanced",
    "ZSTD_sizeof_CCtx",
    "ZSTD_createCDict_advanced",
    "ZSTD_sizeof_CDict",
    "ZSTD_getCParams",
    "ZSTD_getParams",
    "ZSTD_checkCParams",
    "ZSTD_adjustCParams",
    "ZSTD_compress_advanced",
    "ZSTD_isFrame",
    "ZSTD_estimateDCtxSize",
    "ZSTD_createDCtx_advanced",
    "ZSTD_sizeof_DCtx",
    "ZSTD_sizeof_DDict",
    "ZSTD_getDictID_fromDict",
    "ZSTD_getDictID_fromDDict",
    "ZSTD_getDictID_fromFrame",
    "ZSTD_createCStream_advanced",
    "ZSTD_initCStream_srcSize",
    "ZSTD_initCStream_usingDict",
    "ZSTD_initCStream_advanced",
    "ZSTD_initCStream_usingCDict",
    "ZSTD_resetCStream",
    "ZSTD_sizeof_CStream",
    "ZSTD_createDStream_advanced",
    "ZSTD_initDStream_usingDict",
    "ZSTD_initDStream_usingDDict",
    "ZSTD_resetDStream",
    "ZSTD_sizeof_DStream",
    "ZSTD_compressBegin",
    "ZSTD_compressBegin_usingDict",
    "ZSTD_compressBegin_advanced",
    "ZSTD_copyCCtx",
    "ZSTD_compressContinue",
    "ZSTD_compressEnd",
    "ZSTD_getFrameHeader",
    "ZSTD_decompressBegin",
    "ZSTD_decompressBegin_usingDict",
    "ZSTD_copyDCtx",
    "ZSTD_nextSrcSizeToDecompress",
    "ZSTD_decompressContinue",
    "ZSTD_nextInputType",
    "ZSTD_getBlockSize",
    "ZSTD_compressBlock",
    "ZSTD_decompressBlock",
    "ZSTD_insertBlock",
    "ZSTD_getErrorCode",
    "ZSTD_getErrorString",
    "ZBUFF_createCCtx",
    "ZBUFF_freeCCtx",
    "ZBUFF_compressInit",
    "ZBUFF_compressInitDictionary",
    "ZBUFF_compressContinue",
    "ZBUFF_compressFlush",
    "ZBUFF_compressEnd",
    "ZBUFF_createDCtx",
    "ZBUFF_freeDCtx",
    "ZBUFF_decompressInit",
    "ZBUFF_decompressInitDictionary",
    "ZBUFF_decompressContinue",
    "ZBUFF_isError",
    "ZBUFF_getErrorName",
    "ZBUFF_recommendedCInSize",
    "ZBUFF_recommendedCOutSize",
    "ZBUFF_recommendedDInSize",
    "ZBUFF_recommendedDOutSize",
    "ZBUFF_createCCtx_advanced",
    "ZBUFF_createDCtx_advanced",
    "ZBUFF_compressInit_advanced",
    "ZDICT_trainFromBuffer",
    "ZDICT_getDictID",
    "ZDICT_isError",
    "ZDICT_getErrorName",
    "ZDICT_trainFromBuffer_cover",
    "ZDICT_optimizeTrainFromBuffer_cover",
    "ZDICT_trainFromBuffer_fastCover",
    "ZDICT_optimizeTrainFromBuffer_fastCover",
    "ZDICT_finalizeDictionary",
    "ZDICT_trainFromBuffer_legacy",
    "ZDICT_addEntropyTablesFromBuffer"
]

test_filenames = [
    "zstreamtest.c",
    "fuzzer.c",
    "fullbench.c",
    "longmatch.c",
    "legacy.c",
    "poolTests.c",
    "invalidDictionaries.c",
    "decodecorpus.c",
    "../programs/zstdcli.c",
    "../programs/fileio.c",
    "../programs/benchzstd.c",
    "../programs/dibio.c"
]

symbols_found = [False] * len(symbols)

for filename in test_filenames:
    for i, symbol in enumerate(symbols):
        with open(filename, "r") as f:
            txt = f.read()
            if symbol in txt:
                symbols_found[i] = True

missing_symbols = [symbols[i] for i in range(len(symbols)) if not symbols_found[i]]

for symbol in missing_symbols:
	print("{}, ".format(symbol))

```

So it looks like there are a number of missing symbols. I think for the zbuff symbols, we can just run zbufftest.c in the CI somewhere to get rid of manually checking them here. For the remaining ones, I can either write unit tests for them (although it looks like they're all from the deprecated streaming api) or keep symbols.c around with just those symbols (we might just move symbols.c to fuzzer.c because after we remove the zbuff symbols, we will only have a dozen or so symbols to check manually. 

Fine with either direction. Thoughts?

### CODE REVIEW

**Comment by Cyan4973** [comment]
We are also using the CLI during tests, so I guess the list should also be compared to symbols used in `programs/`, such as `zstdcli.c`, `fileio.c`, `benchzstd.c` and `dibio.c` . This will reduce the list of missing symbols further down.

**Comment by bimbashrestha** [comment]
> We are also using the CLI during tests, so I guess the list should also be compared to symbols used in `programs/`, such as `zstdcli.c`, `fileio.c`, `benchzstd.c` and `dibio.c` . This will reduce the list of missing symbols further down.

Ah good point. I included those in the script and it looks like it removed a handful of symbols

**Comment by Cyan4973** [comment]
Good !
So I guess, for the few remaining symbols, it's enough to create one test for each of them, typically within `fuzzer.c`.

`ZBUFF_*` symbols though are special, and should only be tested by `zbufftest`.

**Comment by bimbashrestha** [comment]
> So I guess, for the few remaining symbols, it's enough to create one test for each of them, typically within `fuzzer.c`.

Sure sounds good. I'll put up a separate PR with those later today.
 
> `ZBUFF_*` symbols though are special, and should only be tested by `zbufftest`.

And about this, do we want to run zbufftest in the CI? It's deprecated so I don't kow how much sense that would make. But it would remove the remaining symbols from this list

**Comment by Cyan4973** [comment]
> do we want to run zbufftest in the CI?

We could put this test in the "master only" section of travis CI. This test doesn't need to be run at each PR.

**Comment by bimbashrestha** [comment]
Okay, the only one left now is ZDICT_addEntropyTablesFromBuffer. I can't test this in the fuzzer because it will throw a deprecated warning.

**Comment by Cyan4973** [comment]
We may not need this symbol anymore.
It was never part of the "stable" API, and has been marked as "deprecated" for a long time.

Of course, removing this symbol should be part of another patch.
Also, it's best to wait for next major release (v1.5.0) before removing any symbol.

**Comment by bimbashrestha** [comment]
> Also, it's best to wait for next major release (v1.5.0) before removing any symbol.
Okay, I suppose we should keep symbols.c around till then?

**Comment by Cyan4973** [comment]
> Okay, I suppose we should keep symbols.c around till then?

Just for one obsolete symbol ?
No, it's not worth it.

**Comment by bimbashrestha** [comment]
> Just for one obsolete symbol ? No, it's not worth it.

So just go ahead and rm symbols.c then? 

> Of course, removing this symbol should be part of another patch.

We can probably just do it in this PR since it pretty related no?

**Comment by Cyan4973** [comment]
> So just go ahead and rm symbols.c then?

Yep, and fix any relevant test invoking it.

>> removing this symbol should be part of another patch.

> We can probably just do it in this PR since it pretty related no?

I believe it's cleaner to remove obsolete symbols only when updating `ZSTD_VERSION_MINOR` .
The downside is, we have to "batch" such changes and remember them when `ZSTD_VERSION_MINOR` is updated.

**Pull request merged**
