### PR TITLE
Add Cirrus-CI config and build status badge for testing on FreeBSD

### PR DESCRIPTION
**Pull request by lwhsu**

### CODE REVIEW

**Comment by Cyan4973** [comment]
This is a great idea.
I suspect it must be tied to a few dashboard operations on github and cirrus-CI ?

**Comment by lwhsu** [comment]
Thanks and yes, it requires some dashboard operations.  The setup steps are quite straightforward.  Please refer to https://cirrus-ci.org/guide/quick-start/ and let me know if anything I can help.

**Comment by lwhsu** [comment]
Is there anything I can help?

**Comment by Cyan4973** [comment]
Sorry, just need to free up some time for the dashboard operation part.
That will happen, not sure when, but it will happen.

**Pull request merged**
