### PR TITLE
Integrate ldm with zstdmt

### PR DESCRIPTION
**Pull request by terrelln**
Integrate ldm into zstdmt by running it in serial and in order in the first
step of each job, in the same place as the hash gets updated. The input
buffer is sized to fit the whole LDM window and 2 full buffers of slack.
Input buffers cannot be reused until the LDM step is done with them.
After the LDM step is finished, the jobs don't actually have access to the
full window, only the overlap.

Tested on a few different multi-GB files with and without sanitizers,
and with different numbers of threads.

### CODE REVIEW

**Comment by Cyan4973** [comment]
Any potential benchmark, to compare how it works ?
Typically, `--single-thread` mode vs `1 worker` mode ?
Goal would be to evaluate speed, compression ratio and (if possible, as it is more difficult) memory usage.

**Comment by terrelln** [comment]
I'll add benchmarks before it lands. I've looked at the speed and memory usage, and it looks the same, but I haven't written anything down yet.

**Comment by terrelln** [comment]
To start the more in depth testing I've kicked off `zstreamtest` (`--mt`, `--opaqueapi`, `--newapi`) and `fuzzer`, each with no-sanitizers, UASAN, MSAN, and TSAN, to run for a day.

I'm also going to start the libFuzzer fuzzers, and make sure they get run with LDM and MT.

**Comment by terrelln** [comment]
I benchmarked `--single-thread`, single worker, and multiple workers with and without long range mode. Without long range mode, the memory usage and speed looks the same before and after the patch. With long range mode and `--single-thread` the speed and memory usage look the same. With long range mode and 1+ worker, the memory usage is significantly lower, and the speed is faster for compression levels that aren't bottlenecked by the long range mode.

I'm preparing full benchmarks of the final result compared to `lrzip`.

**Pull request merged**
