### PR TITLE
Fix printing of filesize if >4GB

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by Cyan4973** [comment]
Thanks for the proposed patch.
It looks good to me,

note that CLA compliance is a requirement before the merge.

**Comment by jimis** [comment]
Alright, but it might take a bit since I have to go through my employment contract first. I thought such a small fix was non-copyrightable so the CLA would not be needed.

**Comment by Cyan4973** [comment]
The CLA rules are quite stringent. However, if the process becomes too complex for you, one possible solution could be to duplicate your patch and merge it under another CLA-compliant identity.

**Comment by jimis** [comment]
Thank you for your patience @Cyan4973, I just signed the CLA.

**Review by Cyan4973 — APPROVED** [review]

**Pull request merged**
