### PR TITLE
[cirrus-ci] Removing pkg -y update and using 11.3-snap instead of 11.2 

### PR DESCRIPTION
**Pull request by bimbashrestha**
Testing to see if this will fix the FreeBSD failures

### CODE REVIEW

**Comment by bimbashrestha** [comment]
Well, it looks like this is passing (https://cirrus-ci.com/task/4853445320507392)

It looks like the changes are using 'image_family' instead of 'image', removing the pkg -y update, and removing amd. I think this is fine

**Comment by Cyan4973** [comment]
That's great @bimbashrestha !

Minor detail : it seems we had 2 tests previously, for FreeBSD12 and FreeBSD11,
and now there is only the FreeBSD12 test left.

Is that possible to have FreeBSD11 running again ?

**Comment by bimbashrestha** [comment]
> Is that possible to have FreeBSD11 running again ?

Hopefully that new commit will do it. Lets see:)

**Comment by bimbashrestha** [comment]
Aha. They mention that 11.3 doesn't boot properly at the moment (https://cirrus-ci.org/guide/FreeBSD/). Strange but maybe we can just use freebsd-11-3-snap.

**Comment by bimbashrestha** [comment]
Okay that finally seems to do it. We should probably switch back to using 11.3 stable once they fix the boot issue but until then the snapshot should be fine

**Comment by Cyan4973** [comment]
Excellent ! Thanks @bimbashrestha !

**Pull request merged**
