### PR TITLE
Export a `zstd::libzstd` CMake target if only static or dynamic linkage is specified.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
With this PR, zstd can be referenced from CMake the same way, regardless of whether it was compiled with static or dynamic linkage.

### CODE REVIEW

**Comment by Cyan4973** [comment]
Is there a test checking this property ?

**Comment by teo-tsirpanis** [comment]
I have tested it locally with success, by patching the vcpkg port for zstd.

**Comment by Cyan4973** [comment]
We probably want to add something in CI,
otherwise this property might be lost in a future update.

**Review by Cyan4973 — APPROVED** [review]

**Comment by teo-tsirpanis** [comment]
PR updated to use the same approach as lz4/lz4#1372. By defining the `libzstd` target inside the main CMake project, exporting it gets validated by CMake, making it less error prone.

**Comment by Cyan4973** [comment]
`freebsd-12-4` is no longer available on `Cirrus-ci`.
Not sure why it wants to run this VM version. We have already migrated this test to `FreeBSD-14-0` : 
https://github.com/facebook/zstd/blob/dev/.cirrus.yml .
Maybe the PR just needs to be rebased.

**Review by Cyan4973 — APPROVED** [review]

**Pull request merged**
