### PR TITLE
Replacing divsufsort by libsais

### PR DESCRIPTION
**Pull request by data-man**
- tiny changes in [libsais](https://github.com/IlyaGrebnov/libsais) (using zstd's types, etc.)
- added USE_OPENMP option for makefile

I'm not a licensing expert (libsais is Apache-2.0 Licensed).

### CODE REVIEW

**Comment by data-man** [comment]
OMG, thanks CI! :smile: 
If there are no disagreements in general, I'll continue adapting libsais.

**Comment by IlyaGrebnov** [comment]
Issue reported by 'clang-msan-testzstd' is false positive. Uninitialized read is coming from memory prefetch logic which performs look-ahead into suffix array (workaround is to memset input suffix array).

Other errors related to non compliance with C89/C90 (which are a bit archaic to my taste).

**Comment by data-man** [comment]
@IlyaGrebnov 

> Other errors related to non compliance with C89/C90 

Yes, I know. :smile:
Do you plan to make your library compatible with C89?
Maybe using some macros, like `_DECL_VAR`, `_FOR`, etc.
Will you accept such PR?

**Comment by IlyaGrebnov** [comment]
> Yes, I know. 😄 Do you plan to make your library compatible with C89? Maybe using some macros, like `_DECL_VAR`, `_FOR`, etc. Will you accept such PR?

Yes, I will be willing to accept such PR.

**Comment by data-man** [comment]
Sorry for the rushed PR!
I'll come back to this after my PR(s) to libsais.

**Pull request closed without merging**
