### PR TITLE
Remove additional flag for Visual

### PR DESCRIPTION
**Pull request by senhuang42**
Now that `ZSTD_DISABLE_DEPRECATE_WARNINGS` is in the source code itself, including them in vcxproj files will cause a `C4005 macro redefinition` warning. So we should remove them to avoid appveyor failures.

Test Plan:
- Appveyor

### CODE REVIEW

**Review by Cyan4973 — APPROVED** [review]

**Comment by senhuang42** [comment]
Hmm, appveyor has been queued for over an hour, not sure how to force it to run.

**Comment by Cyan4973** [comment]
We do have a time-length pb with Appveyor tests.
When one specific test should be run swiftly, best way is to cancel all prior runs queued before.

**Comment by senhuang42** [comment]
> We do have a time-length pb with Appveyor tests.
> When one specific test should be run swiftly, best way is to cancel all prior runs queued before.

Ah, it seems like I don't have permissions to cancel any appveyor runs, but the ones on just PRs seem to be a little faster.

**Comment by Cyan4973** [comment]
Appveyor tests moved towards d3634bf9

**Pull request merged**
