### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by supperPants**
A spelling error was found, which could cause a memory leak.

### CODE REVIEW

**Review by Cyan4973 — APPROVED** [review]

**Comment by Cyan4973** [comment]
Nice catch @supperPants !

(note that we will need the CLA process to be completed to merge your contribution)

**Comment by supperPants** [comment]
> A spelling error was found, which could cause a memory leak.



> A spelling error was found, which could cause a memory leak.

**Comment by supperPants** [comment]
@Cyan4973 why were some checks not successful?

**Comment by Cyan4973** [comment]
The CLA was missing. I think it should be fine now. Let's the tests run again.

**Review by Cyan4973 — APPROVED** [review]

**Review by terrelln — APPROVED** [review]

**Pull request merged**
