### PR TITLE
Add test case for PR #972

### PR DESCRIPTION
**Pull request by terrelln**
Will fail before PR #972 is landed.

### CODE REVIEW

**Comment by Cyan4973** [comment]
Thanks  @terrelln !

I completely forgot (or did not notice) that `-o` behavior was changed to allow multiple source files.
I guess I shall update the `v1.3.3` release note to advertise the change.

I also believe the man page has not been updated, as it still pretends that `-o` only works for one source.

**Comment by Cyan4973** [comment]
Wasn't this test supposed to fail ?

I suspect it does not make a difference between a "normal" failure (which is expected) and a segfault.

**Comment by terrelln** [comment]
I messed up initially and it passed. I fixed it for my machine, though it looks like it didn't work on Linux. Looking into it.

**Comment by terrelln** [comment]
Looks like a problem with my shell syntax https://travis-ci.org/facebook/zstd/jobs/324831773#L646.

**Comment by terrelln** [comment]
The tests fail in the expected place now.

**Pull request merged**
