### PR TITLE
Fixes for Windows release

### PR DESCRIPTION
**Pull request by terrelln**
* Put all public headers into `include/`. I didn't include `zbuff.h` since it isn't already included, and is deprecated.
* Export all symbols that have `__declspec(dllexport)` in `libzstd.lib` and delete the `libzstd.def` file since it is no longer used.

This fixes the first 2 problems in Issue #1527.

### CODE REVIEW

**Comment by terrelln** [comment]
@edenhill would you be able to help me verify that the new Artifacts for [x64](https://ci.appveyor.com/project/terrelln/zstd/builds/22501510/job/9b44hxynfrk97lon/artifacts) and [x86](https://ci.appveyor.com/project/terrelln/zstd/builds/22501510/job/4qtatinrr768yrm8/artifacts) fix problem 2? `nm` tells me all the symbols are present, but I can't verify since I don't have a Windows machine.

**Comment by edenhill** [comment]
@terrelln Sorry for slow response, was away on vacation.

I've verified that the non-static .lib/.dlls work with the experimental/advanced feature set, great work!

**Comment by terrelln** [comment]
Thanks for the bug report and help @edenhill!

**Comment by edenhill** [comment]
@terrelln What's the approximate timeline for the next release containing the new build, includes, and directory structure?

**Comment by terrelln** [comment]
We expect to release zstd-1.4.0 in April.

**Pull request merged**
