### PR TITLE
Fix playTests.sh 

### PR DESCRIPTION
**Pull request by Cyan4973**
triggered following visual-release compilation test

### CODE REVIEW

**Comment by terrelln** [comment]
Whats different between this patch and Felix's patch? Does the trailing space matter?

**Comment by terrelln** [comment]
Woohoo, it looks like its fixed! That is such a dumb behavior for Appveyor...

Thanks @Cyan4973 for fixing all the test failures blocking the release!

**Comment by Cyan4973** [comment]
> Does the trailing space matter?

Yes it does,
I presume it could be because in the new `playTests.sh`, @felixhandte made `zstd` and `datagen` an `sh` function, rather than a direct application of an environment variable.

**Comment by terrelln** [comment]
Yeah, I presume it is because the variable is quoted. I made that change to support paths with spaces in the name.

**Pull request merged**
