### PR TITLE
Small fixes to fuzz.py

### PR DESCRIPTION
**Pull request by terrelln**
* Fix a typo.
* Make `zip` work for larger corpora, tested it by updating the regression test corpora.
* Define `BIT_DEBUG` in addition to `ZSTD_DEBUG`.
* Increase the maximum allowed file size to 128 MB.

### CODE REVIEW

**Comment by terrelln** [comment]
CC @Cyan4973 looks like there is a bug in `FSE_bitCost()` (or I'm using it wrong [here]()). Maybe this is why fractional costs are worse?

This assert is failing now that `BIT_DEBUG` is enabled https://github.com/facebook/zstd/blob/dev/lib/common/fse.h#L600. From this caller https://github.com/facebook/zstd/blob/dev/lib/compress/zstd_compress.c#L1666.

**Comment by Cyan4973** [comment]
I'll look into it.
I'm suspecting a problem when `freq[s]==2`.
To be investigated ...

It's a good idea to enable `BIT_DEBUG` for these tests

**Comment by Cyan4973** [comment]
It's actually happening when `freq[s]==0`.
There's a need to specify a behavior for this case.

**Comment by Cyan4973** [comment]
`assert` fix merged into `dev`

**Pull request merged**
