### PR TITLE
Enable RISC-V build & test

### PR DESCRIPTION
**Pull request by alexsifivetw**
Enable RISC-V build & test.

### CODE REVIEW

**Comment by alexsifivetw** [comment]
Seems like the docker image doesn’t run risc-v toolchain & qemu installation. Can any one help me?

https://github.com/facebook/zstd/blob/afcd5da6d4d6c469c536be9f2e72a390c196f49b/.circleci/images/primary/Dockerfile#L10-L16

**Comment by Cyan4973** [comment]
Dependencies in general, and on `docker` images specifically, are to be avoided when practical.
I would rather prefer to rely on standard `apt` packages for CI.
I could get it to run `risc-v` tests properly in [another project](https://github.com/Cyan4973/xxHash/blob/dev/.github/workflows/ci.yml#L386).

**Comment by alexsifivetw** [comment]
> I would rather prefer to rely on standard apt packages for CI.

I agree. We can now use apt to install `riscv-gcc-11`, but only gcc 13 and later versions support RISC-V RVV.
We use `wget` to get latest RISC-V toolchain & QEMU because of our plane for RVV-optimization for `zstd`. 

We could use `apt` to install toolchain, and use `__riscv_v` macro to protect RVV-optimized codes.
This means that the RVV-optimized code would only be enabled when the compiler supports RVV.

However, get RVV-supported toolchain & qemu via `apt` could take long time.

**Comment by alexsifivetw** [comment]
Do you accept installing the toolchain via PPA?

**Comment by Cyan4973** [comment]
> Do you accept installing the toolchain via PPA?

It depends on the PPA,
but in this particular case,
I'm not sure if there is such a need.

RISC-V `qemu` tests are working fine on Github CI using only regular `apt` in another project :
https://github.com/Cyan4973/xxHash/blob/dev/.github/workflows/ci.yml#L386

**Comment by alexsifivetw** [comment]
Hi, I apologize for the late reply.
RISC-V is a young and modern platform. The RISC-V spec, intrinsics, toolchain ... etc, change frequently. Therefore, we need to use the nightly prebuilt toolchain and install it using `wget`.
Would you accept this `wget` method and update the recipe for Docker image?

**Comment by Cyan4973** [comment]
Let's keep it around.
I'll look at it when I get the time.

**Pull request closed without merging**
