### PR TITLE
Make zstd.h compatible with -Wzero-as-null-pointer-constant

### PR DESCRIPTION
**Pull request by r-barnes**
Makes this place nicely when header is used in C++ Files.

### CODE REVIEW

**Review by Cyan4973 — CHANGES_REQUESTED** [review]
This code needs to compile properly on a large base of `C90` compilers.
Please write this modification in a more portable way.

**Comment by r-barnes** [comment]
@Cyan4973 - It looks good now. @terrelln seems happy with the associated D56650471.

**Review by Cyan4973 — APPROVED** [review]
Looks good to me

**Comment by terrelln** [comment]
Thanks @r-barnes!

**Pull request merged**
