### PR TITLE
Fix new typos found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by spaette** [comment]
prettify
skippable

```
$ grep -n pretify zstd/lib/decompress/zstd_decompress_block.c
361: * - pretify output, report below, test with fuzzer to ensure it's correct */
$ grep -n skippeable zstd/lib/decompress/zstd_decompress.c
814: *  `src` must point to the start of a ZSTD frame or a skippeable frame
$ 
```

**Review by Cyan4973 — APPROVED** [review]

**Comment by spaette** [comment]
@Cyan4973 

would like to add a few more changes with your approval

```
$ grep -n "GNUC compatible" zstd/lib/common/portability_macros.h
93: * Only enable assembly for GNUC compatible compilers,
$ grep -nr casted zstd
zstd/lib/compress/zstd_compress.c:2609:    assert(size < (1U<<31));   /* can be casted to int */
$ grep -nr compiation zstd
zstd/build/cmake/CMakeModules/AddZstdCompilationFlags.cmake:60:        # EnableCompilerFlag("-std=c99" true false)   # Set C compiation to c99 standard
$ grep -nr ditionary zstd
zstd/CHANGELOG:492:fix : bug #944 : multithreading with shared ditionary and large data, reported by @gsliepen
$ grep -nr relevants zstd
zstd/lib/compress/zstd_compress.c:5625: *            into its relevants cParams.
$ grep -nr trigging zstd
zstd/lib/common/compiler.h:329: * Helper function to perform a wrapped pointer difference without trigging
$ 
```

fixes for above

```
sed -i "s/GNUC compatible/GNU C compatible/g" zstd/lib/common/portability_macros.h
sed -i "s/casted/cast/g" zstd/lib/compress/zstd_compress.c
sed -i "s/compiation/compilation/g" zstd/build/cmake/CMakeModules/AddZstdCompilationFlags.cmake
sed -i "s/ditionary/dictionary/g" zstd/CHANGELOG
sed -i "s/relevants/relevant/g" zstd/lib/compress/zstd_compress.c
sed -i "s/trigging/triggering/g" zstd/lib/common/compiler.h
```
<hr>

@DimitriPapadopoulos

for the record `approximatively` appears in the Oxford dictionary

easier to read however with your change of that string

**Comment by Cyan4973** [comment]
@spaette 
These suggestions look good to me

**Comment by DimitriPapadopoulos** [comment]
Indeed `approximatively` appears in the [OED](https://www.oed.com/search/dictionary/?q=approximatively). It is missing from other mainstream curated dictionaries, and perhaps more importantly (?) is missing from [SCOWLS (and friends)](http://app.aspell.net/lookup?dict=en_US-large;words=approximatively) which I see as the reference dictionary for open source spell checking.

**Comment by DimitriPapadopoulos** [comment]
I have added all your suggestions.

**Review by Cyan4973 — APPROVED** [review]

**Comment by spaette** [comment]
the .c, .h, and .cmake files' changes are limited to comments which shouldn't account for the 2 failed checks

**Pull request merged**
