### PR TITLE
Pzstd should now compile with gcc

### PR DESCRIPTION
**Pull request by terrelln**
There were small issues with flags and missing includes.

### CODE REVIEW

**Comment by terrelln** [comment]
Still an issue with travis's g++ version, it doesn't support C++ 11.

**Comment by Cyan4973** [comment]
Still some issues apparently : 

```
g++ -I../../lib -I../../lib/common -I../../lib/dictBuilder -I../../programs -I. -O3 -std=c++11   -c Pzstd.cpp -o Pzstd.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
```

maybe a problem of g++ version.
default compiler is quite old in Travis.

**Comment by terrelln** [comment]
Yup, I'm updating the default g++ to 4.8 for CXX, but I'll leave CC alone.

**Comment by Cyan4973** [comment]
Considering latest test result,
https://travis-ci.org/facebook/zstd/jobs/156989526
I suspect a missing dependency.

**Comment by terrelln** [comment]
It finally works 😄

**Pull request merged**
