### PR TITLE
NuGet package builder

### PR DESCRIPTION
**Pull request by edenhill**
Also see the issues reported in #1527.

Example usage from a C project in  https://github.com/edenhill/librdkafka/commit/f5107430c1d32f5be850f122c4832d69f42d7cf5

### CODE REVIEW

**Comment by terrelln** [comment]
Taking a look at the README, do you need some sort of permissions to upload a new package to NuGET (out of curiosity)?

**Comment by edenhill** [comment]
Sign up on NuGet.org (preferably with a Microsoft account), and then upload packages manually through the web UI.
You can also create an access key and use the `nuget push ..` utility to upload from the command line.
I also think AppVeyor can upload artifacts directly.

**Comment by edenhill** [comment]
Will update this PR when new win releases are available with the new structure, as changed in #1531

**Comment by terrelln** [comment]
zstd-1.4.0 has been released, which has the new structure.

**Comment by bruno-garcia** [comment]
Any updates on this? I'm stuck trying to use `zlib` from .NET on a macOS (.NET Core).
Could send a PR after to build the NuGet packages to support not only Windows but also macOS.

**Comment by Cyan4973** [comment]
Joining in.

If I understand correctly, this PR offers a script to generate a Nuget package.

Its dependencies are : names provided to Windows binary packages in the "release" section, and their content (and directory tree).
It's worth mentioning because, also we don't plan to change these things often, it's all too easy to have a change once in a while, and it would be enough to break the script.

And by the way, it seems @terrelln mentions a change in the Windows binary package for `v1.4.0`, so it seems the script in this PR should be updated ?

Also : 
Running the script to create a package locally is one thing, actually pushing it on nuget.org is another one, with its own administrative burden. While I might be able to do it, I wonder if it's the best course of action, since I'm not myself a nuget user, hence I probably don't understand the use cases, and can easily miss its maintenance.

Also, I note that there are already 3 nuget packages proposed with some `zstd` flavor, listed at : 
https://www.nuget.org/packages?q=Tags%3A%22zstd%22

and I'm not yet clear what this one would offer on top of existing ones. 

I must read more the history of exchanges...

**Comment by Cyan4973** [comment]
This PR hasn't changed much in the last few months.
Is it still active ? or should it be closed ?

**Pull request closed without merging**
