### PR TITLE
Update Copyright Comments

### PR DESCRIPTION
**Pull request by felixhandte**
T106302328 wants us to update to "`Meta Platforms, Inc. and affiliates`".

In addition, I cleaned up some lagging year ranges, rewriting their ends to "`present`". If there's a reason it should be an explicit year though, I can switch to "`2022`".

### CODE REVIEW

**Comment by Cyan4973** [comment]
It seems we were told at some point that `present` wasn't a valid year, and that an actual date was necessary.

**Comment by terrelln** [comment]
> It seems we were told at some point that present wasn't a valid year, and that an actual date was necessary.

That is not the latest guidance. We should move everything to a yearless copyright.

**Comment by terrelln** [comment]
Just `Copyright (c) Meta Platforms, Inc. and affiliates.` is fine. https://www.internalfb.com/intern/wiki/Open_Source/Licenses/

**Comment by JunHe77** [comment]
Sorry for just jumping in for a related copyright question. 😄 
Is a new file, like the new .S file in #3155 required to share copyright with Meta? I saw the check in [test-licens.py](https://github.com/facebook/zstd/blob/dev/tests/test-license.py#L117-L121), but [exceptions](https://github.com/facebook/zstd/blob/dev/tests/test-license.py#L60-L67) also exist.

**Comment by Tachi107** [comment]
> In addition, I cleaned up some lagging year ranges, rewriting their ends to "`present`". If there's a reason it should be an explicit year though, I can switch to "`2022`".

I don't want to mess with corporation policies, but I'd recommend giving [this blog post](https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code#why-not-bump-the-year-on-change) a quick read - in short routinely bumping copyright years isn't really that worth it :)

**Comment by Cyan4973** [comment]
There is no more reference of any year in the copyright header.
Is that a wanted outcome ?

**Comment by felixhandte** [comment]
@Cyan4973, that seems to be [the guidance](https://www.internalfb.com/intern/wiki/Open_Source/Licenses/).

**Review by Cyan4973 — APPROVED** [review]

**Pull request merged**
