### PR TITLE
Fix zstd not erroring on compressing to terminal without forceStdout

### PR DESCRIPTION
**Pull request by iburinoc**
Not sure I understand why the condition was the way it was before, but I don't think this should break any case that worked properly before.

Fixes this case writing compressed data to term:
```
echo bob | zstd
```

### CODE REVIEW

**Comment by Cyan4973** [comment]
We would need to add a test case to ensure such issue is detected in the future

**Comment by Cyan4973** [comment]
Almost there

Apparently, something doesn't work on Windows. Maybe the `IS_CONSOLE()` detection routine.
To be investigated...

**Comment by iburinoc** [comment]
Can't reproduce locally, it works fine in my Windows VM.  I suspect the problem is that appveyor doesn't pretend to be a terminal to the scripts so IS_CONSOLE returns 0, I guess the best solution here is to just not run that test on windows.

**Comment by Cyan4973** [comment]
Indeed, maybe `stdin` and `stdout` are not detected as console within Appveyor.
Could it be similar to : 
https://github.com/lz4/lz4/issues/308

In which case some similar solution may apply : 
https://github.com/lz4/lz4/issues/308#issuecomment-275030972

**Comment by iburinoc** [comment]
Hmm, doesn't seem to work, tried [https://github.com/iburinoc/zstd/commit/69ead66018812a6cd996d40db0be732a3366b6a2](https://github.com/iburinoc/zstd/commit/69ead66018812a6cd996d40db0be732a3366b6a2).  Passes locally, fails on appveyor.  Seems like that solution only works when `/dev/tty`/`CON` actually points to a real TTY.  It worked for LZ4 because the case that was tested was `make -C tests test | cat`, so `/dev/tty` still existed.  This doesn't seem to work in a truly tty-less environment, such as by detaching it from the terminal with setsid (`./playTests.sh: line 78: /dev/tty: No such device or address`).

**Comment by Cyan4973** [comment]
OK, so I guess the fix is to disable the test for Windows ?

**Comment by iburinoc** [comment]
I guess, yeah.  It still feels fragile to have that test there on other platforms and fail if playTests.sh isn't run from a terminal, I'll look at disabling it if `stdin`/`stdout` aren't TTYs.

**Comment by Cyan4973** [comment]
good fix @iburinoc !

**Pull request merged**
