### PR TITLE
Add 64-bit detection for LoongArch

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.

Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:

### CODE REVIEW

**Comment by Cyan4973** [comment]
Is there any `LoongArch` core for `qemu` that could be added to CI,
so that we can test that this PR works,
and ensure that the architecture remains supported in the future (in case a contribution would break such support) ?

_edit_ : mmmh, according to [this article](https://www.phoronix.com/news/QEMU-7.1-Released), support for LoongArch in `qemu` is _very_ recent, so that might not be practical for CI (yet)...

**Comment by ilyakurdyukov** [comment]
```
  || defined _LP64 || defined __LP64__ /* NetBSD, OpenBSD */ || defined __64BIT__ /* AIX */ || defined _ADDR64 /* Cray */               \
  || (defined __SIZEOF_POINTER__ && __SIZEOF_POINTER__ == 8) /* gcc */
```

I want to note that good compilers should use some of these macros. So if your compiler doesn't define any of these macros, you should file a bug report for that compiler so you don't have to add your new architecture to every whitelist of 64-bit architectures.

**Comment by xry111** [comment]
GCC has `__LP64__` for 64-bit LoongArch target:

```
$ lscpu | grep Arch
Architecture:        loongarch64
$ echo __LP64__ | cpp -nostdinc
# 0 "<stdin>"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "<stdin>"
1
```

**Comment by ilyakurdyukov** [comment]
> GCC has `__LP64__` for 64-bit LoongArch target:

Then this patch is not needed. It looks like some Chinese people want to add a reference to LoongArch to every project, even if it's absolutely unnecessary.

**Comment by xry111** [comment]
And `__loongarch64` is deprecated (see table 15 in [the doc](https://loongson.github.io/LoongArch-Documentation/LoongArch-toolchain-conventions-EN.html)) because we don't really know if it means `__loongarch_lp64` (the ABI) or `__loongarch_grlen == 64` (the HW register).

I think we would add a deprecate warning for it into GCC considering many developers don't RTFM.

**Comment by Cyan4973** [comment]
OK, in essence, this does not seem a useful macro to add

**Pull request closed without merging**
