### PR TITLE
meson: fix build by adding missing files

### LINKED ISSUE #2519: 1.4.9: build fails
Source tree is configured with:
```
%meson \
        -D backtrace=false \
        -D build_programs=true \
        -D build_tests=true \
        -D debug_level=0 \
        -D lz4=disabled \
        -D lzma=disabled \
        -D multi_thread=enabled \
        -D static_runtime=false \
        -D zlib=disabled \
        %{nil}
```
And it fails with:
```
[tkloczko@barrel x86_64-redhat-linux-gnu]$ ninja
[1/4] Linking target lib/libzstd.so.1.4.9
FAILED: lib/libzstd.so.1.4.9
/usr/bin/gcc  -o lib/libzstd.so.1.4.9 lib/libzstd.so.1.4.9.p/.._.._.._lib_common_entropy_common.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_common_fse_decompress.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_common_threading.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_common_pool.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_common_zstd_common.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_common_error_private.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_common_xxhash.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_hist.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_fse_compress.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_huf_compress.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstd_compress.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstd_compress_literals.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstd_compress_sequences.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstd_compress_superblock.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstdmt_compress.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstd_fast.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstd_double_fast.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstd_lazy.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstd_opt.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_compress_zstd_ldm.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_decompress_huf_decompress.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_decompress_zstd_decompress.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_decompress_zstd_decompress_block.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_decompress_zstd_ddict.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_dictBuilder_cover.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_dictBuilder_fastcover.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_dictBuilder_divsufsort.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_dictBuilder_zdict.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_deprecated_zbuff_common.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_deprecated_zbuff_compress.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_deprecated_zbuff_decompress.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_legacy_zstd_v05.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_legacy_zstd_v06.c.o lib/libzstd.so.1.4.9.p/.._.._.._lib_legacy_zstd_v07.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libzstd.so.1 -Wl,--end-group -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -pthread
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid abstract instance DIE ref
/tmp/cc3BMINj.lto.o: in function `ZSTD_CCtx_trace':
<artificial>:(.text+0x63aee): undefined reference to `ZSTD_trace_compress_end'
/usr/bin/ld: /tmp/cc3BMINj.lto.o: in function `ZSTD_compressBegin_internal':
<artificial>:(.text+0x6d83a): undefined reference to `ZSTD_trace_compress_begin'
/usr/bin/ld: /tmp/cc3BMINj.lto.o: in function `ZSTD_CCtx_init_compressStream2':
<artificial>:(.text+0x6f500): undefined reference to `ZSTD_trace_compress_begin'
/usr/bin/ld: /tmp/cc3BMINj.lto.o: in function `ZSTD_compress_advanced_internal':
<artificial>:(.text+0x72972): undefined reference to `ZSTD_trace_compress_begin'
/usr/bin/ld: /tmp/cc3BMINj.lto.o: in function `ZSTD_decompressBegin':
<artificial>:(.text+0x76159): undefined reference to `ZSTD_trace_decompress_begin'
/usr/bin/ld: /tmp/cc3BMINj.lto.o: in function `ZSTD_DCtx_trace_end.part.0':
<artificial>:(.text+0x78a12): undefined reference to `ZSTD_trace_decompress_end'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by SupervisedThinking**
fixes https://github.com/facebook/zstd/issues/2519 by https://github.com/facebook/zstd/issues/2519#issuecomment-790092538

### CODE REVIEW

**Review by senhuang42 — APPROVED** [review]
Looks great! Thanks @SupervisedThinking !

**Comment by SupervisedThinking** [comment]
> Looks great! Thanks @SupervisedThinking !

Well @kloczek did the job but since I use meson too fixing it upstream made sense 👍🏻

**Comment by kloczek** [comment]
Sorry I was busy and had no time to prepare PR :/

**Comment by SupervisedThinking** [comment]
> Sorry I was busy and had no time to prepare PR :/

NP - since you posted the patch I could PR it 🥇

**Pull request merged**
