### PR TITLE
Various Macros to Allow Building Extremely Minimal Decoder Library

### PR DESCRIPTION
**Pull request by felixhandte**
For a couple upcoming use cases, it is of paramount importance to produce absolutely the smallest possible Zstd decompressor. This changeset adds a number of macros that can be set to selectively disable various parts of the codebase that normally use verbosity/redundancy to achieve performance and feature-richness. Full ability to decompress all valid zstd blobs is retained.

The macros are:

- `ZSTD_NO_INLINE`: disables inline statements.
- `ZSTD_STRIP_ERROR_STRINGS`: replaces all error strings with a single one.
- `ZSTD_DECOMPRESS_MINIMAL`: removes the `ZSTD_decompressSequencesLong` path.
- `HUF_DECOMPRESS_MINIMAL`: removes the two-at-a-time (`X2`) huffman decoder implementations.

I am very open to changing the approach taken. Just want to put it up to get some initial thoughts.

## Possible Extensions / To-Do

- Add a makefile target that builds the minimal decompressor library with these flags set.
- Set these flags in contbuild tests.

## Performance

I compared an absolute minimal build with a regular one on x86_64. I built the regular binary with `make clean zstd` and the minimal library with

```
make clean zstd MOREFLAGS="-Os -s -fno-stack-protector -fomit-frame-pointer -ffunction-sections -fdata-sections -fmerge-all-constants -fno-ident -Wl,--gc-sections -Wl,-z,norelro -Wl,--hash-style=gnu -Wl,--build-id=none -flto -DDEBUGLEVEL=0 -DZSTD_NODICT -DNDEBUG -DDYNAMIC_BMI2=0 -DHUF_DECOMPRESS_MINIMAL -DZSTD_DECOMPRESS_MINIMAL -DZSTD_NO_INLINE -DZSTD_STRIP_ERROR_STRINGS"
```

I saw decompression speeds of ~1250MB/s and ~525MB/s, respectively (via `zstd -b`).

### CODE REVIEW

**Comment by Cyan4973** [comment]
This is a great start, and it has already allowed you to test the lower bound of the decoder binary size.
Here are a few thoughts : 
- The performance impact is pretty strong. It aggregates all sort of size optimizations, from compiler settings, to different branch reductions strategies. So it's difficult to know how much each element contributes to the formula
    + try to keep track of the gains / losses for each of them. These optimizations can be expected to feature vastly different trade off, some being very efficient at reducing code size at a minor speed cost, some offering less reduction and maybe impacting speed more severely. You'll want to offer users some enlightened choice between these options.
- Both `ZSTD_DECOMPRESS_MINIMAL` and `HUF_DECOMPRESS_MINIMAL` select one branch and remove the other one. But we could imagine selecting the opposite, keeping the _other_ branch.
    + make it possible to select one _or_ the other branch. Document the impact, which is likely to be different, and may even depend on source (small/large input).
- Finally, since this option is developed for mobile, it will be important to make those tests on ARM. It's already possible to test binary size through cross-compilation (on Linux typically). Speed impact though will be different : not only it requires real hardware, it also may vary depending on hardware.
    + this can be done later. What matters now is to build the methodology to run those tests.

**Comment by felixhandte** [comment]
More detailed performance figures!

All benchmarks were built with `gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0` with base flags

```
  -fno-stack-protector \
  -fomit-frame-pointer \
  -ffunction-sections \
  -fdata-sections \
  -fmerge-all-constants \
  -fno-ident \
  -flto \
  -DDYNAMIC_BMI2=0 \
  -DZSTD_NODICT \
  -DZSTD_LEGACY_SUPPORT=0 \
  -DDEBUGLEVEL=0 \
  -DNDEBUG \
  -Wl,--gc-sections \
  -Wl,-z,norelro \
  -Wl,--hash-style=gnu \
  -Wl,--build-id=none
```

Benchmark decompression speeds gathered with `zstd -b3`.

Column | Macro
----- | -----
1 | `HUF_FORCE_DECOMPRESS_X1`
2 | `HUF_FORCE_DECOMPRESS_X2`
3 | `ZSTD_FORCE_DECOMPRESS_SEQUENCES_SHORT`
4 | `ZSTD_FORCE_DECOMPRESS_SEQUENCES_LONG`
5 | `ZSTD_NO_INLINE`
6 | `ZSTD_STRIP_ERROR_STRINGS`

`-O` | 1 | 2 | 3 | 4 | 5 | 6 | Size | Gz | Speed
----- | ---- | ---- | ------- | ------ | ----------- | ----------- | ---- | ------- | -----
`3` | | | | | | | 64048 | 33641 | 999 MB/s
`s` | | | | | | | 35680 | 18761 | 682 MB/s
`s` |Y| | | | | | 31032 | 16218 | 552 MB/s
`s` | |Y| | | | | 32216 | 17104 | 667 MB/s
`s` | | |Y| | | | 32296 | 16899 | 783 MB/s
`s` | | | |Y| | | 34096 | 17807 | 644 MB/s
`s` | | | | |Y| | 31648 | 17508 | 676 MB/s
`s` |Y| |Y| | | | 27248 | 14453 | 595 MB/s
`s` |Y| |Y| |Y| | 26168 | 14067 | 585 MB/s
`s` |Y| |Y| |Y|Y| 24952 | 13306 | 580 MB/s

**Comment by Cyan4973** [comment]
These are great results @felixhandte ,
it gives a good sense of control, 
why each option exist, what's its impact, and why it's selected.

Quick note : 
I'm surprised that speed of line 3 (`552 MB/s`) which only uses `HUF_FORCE_DECOMPRESS_X1`
seems slower than later combinations of build macros (`580 MB/s`) ?

**Comment by felixhandte** [comment]
@Cyan4973, I think that must be because line 5, which just adds `ZSTD_FORCE...SHORT` is _faster_ than line 2 (just `-Os`). Given that, it's not crazy for `HUF_FORCE...X1 + ZSTD_FORCE...SHORT` to be faster than just `HUF_FORCE...X1`.

**Comment by Cyan4973** [comment]
Be sure to document these new build macros in `lib/README.md`

**Comment by Cyan4973** [comment]
The minimal decompressor test is too long, and just times outs.
Maybe reduce the nb of things to test with these builds ?

Also  : try to turn on `-Werror`, it will help catching more issues,
such as this one :
https://travis-ci.org/facebook/zstd/jobs/470205284#L471

**Pull request merged**
