### PR TITLE
[x-compile] Fix cross-compiling for AArch64 with lld

### PR DESCRIPTION
**Pull request by jcelerier**
Fix cross-compilation from Linux x86_64 to AArch64 using a clang / lld toolchain.

LLVM's lld refuses to link in a .a file where some .S.o files do not match the target architectures (e.g. linking together main.o AArch64 + libzstd.a (AArch64+AMD64) fails)

This adds the huf_decompress_amd64.S file only for AMD64 targets in the CMake toolchain.

### CODE REVIEW

**Comment by Cyan4973** [comment]
Note that the CLA process is mandatory, and we can't proceed with merging this contribution as long as it's not completed.

Also : build fails, showing that more work is needed to modify the `cmake` script safely:
https://github.com/facebook/zstd/actions/runs/6214707557/job/16867528643?pr=3760#step:3:320

**Comment by jcelerier** [comment]
@Cyan4973 hmm I filled the CLA thing as soon as I got the mail? doing it again..

Investigating the issue too, I hadn't seen the build failure, my bad

**Comment by Cyan4973** [comment]
One of the flagged issues, the `x32` test, is unrelated to this PR, has been fixed recently.
You may want to rebase your PR on top of `dev` to make it pass this test.

**Comment by jcelerier** [comment]
I added a debug print to check what's the expected value of CMAKE_SYSTEM_PROCESSOR, I couldn't find a clear answer so the next build will fail with an expected FATAL_ERROR

**Review by Cyan4973 — APPROVED** [review]

**Comment by Cyan4973** [comment]
What's the exact compilation scenario fixed by this patch,
and could it be added as part of the test suite ?

**Comment by jcelerier** [comment]
> What's the exact compilation scenario fixed by this patch,

Host toolchain on Linux x86-64: clang / libc++ / lld (as provided by arch linux)
Target: AArch64
(I had this issue while cross-compiling for a raspberry pi).

I can try to add such a toolchain to the CI - where would be the best way to put it ?

**Comment by Cyan4973** [comment]
> I can try to add such a toolchain to the CI - where would be the best way to put it ?

Probably as part of `dev/.github/workflows/dev-short-tests.yml`

**Comment by jcelerier** [comment]
hmm, I'm looking into it but it looks kinda messy - at least there are quite a few steps involved: 

- downloading an LLVM amd64 host
- downloading an LLVM aarch64 target (yes, LLVM is _technically_ a cross-compiler but the amd64 package does not ship with the required aarch64 headers & lib files such as clang-rt, libcxx, etc. and conversely, so in the end you still need to download both)
-  bonus: the current latest LLVM release does not seem to have AMD64 Linux host packages: https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.1 (the aarch64 is there though.. but it's not possible to cross-compile from e.g. clang X.0 with the clang lib files (X+1).0 and I'd like this test to use the latest released LLVM
- downloading an aarch64 sysroot to compile against for the linux and libc headers - I extracted mine manually from the raspberry pi image as that's what I'm targetting, I guess it'd be possible to extract it from the docker image through `docker save arm64v8/debian:latest -o image.tar` BUT we need to install the aarch64 glibc headers & friends thus there is some qemu involved...
- toolchain file: here's mine :

```cmake
set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(rootfs_dir /PATH/TO/sysroot)
set(llvm_version 16)
set(llvm_host_dir /PATH/TO/llvm-${llvm_version})
set(llvm_target_dir /PATH/TO/llvm-${llvm_version}-aarch64)
set(rpi_incdir ${rootfs_dir}/usr/include)

set(CMAKE_C_COMPILER ${llvm_host_dir}/bin/clang)
set(CMAKE_CXX_COMPILER ${llvm_host_dir}/bin/clang++)
set(CMAKE_SYSROOT ${rootfs_dir})
set(CMAKE_FIND_ROOT_PATH ${rootfs_dir})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:--target=aarch64-unknown-linux-gnu>")
add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:--sysroot=${rootfs_dir}>")
add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:-resource-dir;${llvm_target_dir}/lib/clang/${llvm_version}>")
add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:-rtlib=compiler-rt>")
add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:-nostdinc>")
add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-nostdinc++>")
add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:SHELL:-Xclang -internal-isystem -Xclang  ${llvm_target_dir}/include/aarch64-unknown-linux-gnu/c++/v1>")
add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:SHELL:-Xclang -internal-isystem -Xclang  ${llvm_target_dir}/include/c++/v1>")
add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:SHELL:-Xclang -internal-isystem -Xclang ${llvm_target_dir}/lib/clang/${llvm_version}/include>")
add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:SHELL: -Xclang -internal-externc-isystem -Xclang ${rootfs_dir}/usr/include>")
add_compile_options("$<$<COMPILE_LANGUAGE:C,CXX>:SHELL: -Xclang -internal-externc-isystem -Xclang ${rootfs_dir}/usr/include/aarch64-linux-gnu>")

add_link_options("$<$<COMPILE_LANGUAGE:C,CXX>:--target=aarch64-unknown-linux-gnu>")
add_link_options("$<$<COMPILE_LANGUAGE:C,CXX>:--sysroot=${rootfs_dir}>")
add_link_options("$<$<COMPILE_LANGUAGE:C,CXX>:-resource-dir;${llvm_target_dir}/lib/clang/${llvm_version}>")
add_link_options("$<$<COMPILE_LANGUAGE:C,CXX>:-rtlib=compiler-rt>")
add_link_options("$<$<COMPILE_LANGUAGE:C,CXX>:-fuse-ld=lld>")
add_link_options("$<$<COMPILE_LANGUAGE:CXX>:-nostdlib++>")
add_link_options("$<$<COMPILE_LANGUAGE:CXX>:${llvm_target_dir}/lib/aarch64-unknown-linux-gnu/libc++.a>")
add_link_options("$<$<COMPILE_LANGUAGE:CXX>:${llvm_target_dir}/lib/aarch64-unknown-linux-gnu/libc++abi.a>")
add_link_options("$<$<COMPILE_LANGUAGE:CXX>:${llvm_target_dir}/lib/aarch64-unknown-linux-gnu/libunwind.a>")
```

hence my question : is there already some X-compilation scenario tested by the CI that I could leverage / reuse instead of heavy-handedly applying my stuff?

**Comment by Cyan4973** [comment]
We do have cross-compiling scenarios,
but they use `gcc`, not `clang`.

**Pull request merged**
