### PR TITLE
Add a link to an alternative binding for Go

### PR DESCRIPTION
**Pull request by valyala**

### CODE REVIEW

**Comment by Cyan4973** [comment]
Thanks for the link @valyala .
Do you have any simple differentiator compared to existing version that would help people to decide which version to use ?

**Comment by valyala** [comment]
@Cyan4973 , below are major highlights for [gozstd](https://github.com/valyala/gozstd) comparing to [the existing zstd Go wrapper](https://github.com/DataDog/zstd):

1. `gozstd` vendors upstream zstd code without any modifications inside [zstd folder](https://github.com/valyala/gozstd/tree/master/zstd). Upstream zstd code may be easily updated with a simple [Makefile rule](https://github.com/valyala/gozstd/blob/master/Makefile) - `update-zstd`. The existing go wrapper mixes upstream zstd code with Go code [in a single folder](https://github.com/DataDog/zstd/tree/aebefd9fcb99f22cd691ef778a12ed68f0e6a1ab). It us unclear how to update upstream zstd code there.

2. It uses more efficient upstream zstd API for streaming implementation. This API avoids existing issues form the existing Go wrapper - see [this one](https://github.com/DataDog/zstd/issues/22) and [this one](https://github.com/DataDog/zstd/issues/16).

3. It properly implements [stream flushing](https://godoc.org/github.com/valyala/gozstd#Writer.Flush), so it works as expected in network applications.

4. Its tests have [close to 100% code coverage](https://codecov.io/gh/valyala/gozstd).

5. Its API is [easier to use](https://godoc.org/github.com/valyala/gozstd). The API is designed with performance in mind, so it may be easily used in low overhead mode.

6. `gozstd` has better dictionary support.

**Comment by valyala** [comment]
Thanks!

**Comment by develar** [comment]
Not clear why you have decide to start a new project instead of contributing to existing :) And  linux/amd64 is a blocker limitation to try gozstd :)

**Comment by valyala** [comment]
It is easier to start a new small project instead of trying to push desired changes into existing project :)

There is a [pending PR](https://github.com/valyala/gozstd/pulls) that adds `darwin/amd64` and `windows/amd64` support. Support for other platforms may be easily added by users of these platforms following the pattern in the PR.

**Pull request merged**
